apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}-redis
spec:
  {{ if not .Values.withoutStorage }}
  volumeClaimTemplates:
    - metadata:
        name: redis
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  {{ end }}
  selector:
    matchLabels:
      app: {{.Release.Name}}-redis
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-redis
    spec:
      containers:
        - name: main
          image: redis
          resources:
            requests:
              cpu: 30m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 80Mi
          ports:
            - containerPort: 6379
          {{ if not .Values.withoutStorage }}
          volumeMounts:
            - mountPath: /data
              name: redis
          {{ end }}
      {{ if not .Values.withoutStorage }}
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis
      {{ end }}
